---
title: "Surrogate pairs"
author: "Céline Carlsen"
date: "15/11/2017"
output: html_document
---
For all those who have been struggling with the surrogate pairs.
It turns out there are some problems with the code Celine shared with us, and I thought I would say how to fix (some of) them.
Thanks to Karl and his group for helping!
Step 1: There can be some problems with the working directory, for those of us who are not used to changing it all the time. I solved this by just putting all my files into the main folder where my working directory is by default and working from there.
Step 2: Sometimes, the line
pairs=as.numeric(unique(df$V2))
Can give some trouble. A way to fix this is by changing it to
pairs=as.numeric(unique(as.numeric(as.character(df$V2))))
Step 3:
In the end of the code, there are four sets of code each looking something like this:
d5=data.frame(Resp1=d1$Resp1,Resp2=d2$Resp1,HR1=d1$HR1,HR2=d2$HR1,Resp1S=d1$Resp1S,Resp2S=d2$Resp1S,HR1S=d1$HR1S,HR2S=d2$HR1S)
They should be changed to look like this:
d5=data.frame(Resp1=d1$Resp1,Resp2=d2$Resp1,HR1=d1$HR1,HR2=d2$HR1,Resp1S=d1$Resp1,Resp2S=d2$Resp1,HR1S=d1$HR1,HR2S=d2$HR1)
(Deleting the S'es after the dollar signs, but not the ones before)
Remember to do it for all four sets of code.
Step 4:
There has to be a folder called "surrogate" in the working directory for the files to be put in
Good luck!




```{r}

setwd("/Users/celinecarlsen/Cognitive Science/5. semester/TA Methods III/Assingments/A4_coordination/A4/downsampled")
prepro_filelist = list.files(pattern = "Study1") # load the preprocessed files

num=str_extract_all(prepro_filelist, "\\d+") #extract all numbers in the file name (i.e Study?_G?_T?)

df= as.data.frame(t(as.data.frame(num))) #create a transposed (i.e. "tipped") dataframe of these number
rownames(df)<-NULL #Remove rownames.

pairs=as.numeric(unique(df$V2)) #create pairs, i.e. unique group numbers

SurrogateList <- expand.grid(a = pairs, b = pairs) # expand.grid combines all possible combinations of a given vector
SurrogateList = subset(SurrogateList, a != b) # Ensure that pair 1 (i.e group1) doesn't get paired with it self.


# Per each condition
for (co in c("Synchronous","TurnTaking","SelfPaced")){ #loop through a list of condintions 
  for (i in 1:nrow(SurrogateList)){ #and loop through all the pairings of the surrogate list
    
  #start recreate filenames from the working directory based on the matching from the surrogatelist
  f1=paste0('Study1_G',SurrogateList$a[i]) #Insert group numeber from Surrogatelist 
  f2=paste0('Study1_G',SurrogateList$b[i])
  
  file1=prepro_filelist[grepl(f1,prepro_filelist) & grepl(co,prepro_filelist)] #insert conditions as well.
  file2=prepro_filelist[grepl(f2,prepro_filelist) & grepl(co,prepro_filelist)]
  
  d1=read.csv(file1) #Load the recreated filenames
  
  d2=read.csv(file2) 
  
  #Ensure both dataframes have the same length
  if (nrow(d1)>nrow(d2)){
    d1=d1[1:nrow(d2),]
  } else {
    d2=d2[1:nrow(d1),]
  }
  
  #creation of surrogate files. (Riccardo's idea of having fun and completely overdoing it ;-) ) 
  #per each 2 pairs there are 4 possible surrogate pairs: 
  #pair1person1 w pair2person2; 
  d3=data.frame(Resp1=d1$Resp1,Resp2=d2$Resp2,HR1=d1$HR1,HR2=d2$HR2,Resp1S=d1$Resp1S,Resp2S=d2$Resp2S,HR1S=d1$HR1S,HR2S=d2$HR2S)
  #pair1person2 w pair2person2;
  d4=data.frame(Resp1=d2$Resp1,Resp2=d1$Resp2,HR1=d2$HR1,HR2=d1$HR2,Resp1S=d2$Resp1S,Resp2S=d1$Resp2S,HR1S=d2$HR1S,HR2S=d1$HR2S)
  
  #pair1person1 w pair2person1;
  d5=data.frame(Resp1=d1$Resp1,Resp2=d2$Resp1,HR1=d1$HR1,HR2=d2$HR1,Resp1S=d1$Resp1S,Resp2S=d2$Resp1S,HR1S=d1$HR1S,HR2S=d2$HR1S)
  #pair1person2 w pair2person2
  d6=data.frame(Resp1=d2$Resp2,Resp2=d1$Resp2,HR1=d2$HR2,HR2=d1$HR2,Resp1S=d2$Resp2S,Resp2S=d1$Resp2S,HR1S=d2$HR2S,HR2S=d1$HR2S)
  
  #Make filenames that tells which pairs have been mixed
  file3=paste0("Study1_SurrogateGroup",SurrogateList$a[i],"&",SurrogateList$b[i],"a_",co,".csv")
  file4=paste0("Study1_SurrogateGroup",SurrogateList$a[i],"&",SurrogateList$b[i],"b_",co,".csv")
  file5=paste0("Study1_SurrogateGroup",SurrogateList$a[i],"&",SurrogateList$b[i],"c_",co,".csv")
  file6=paste0("Study1_SurrogateGroup",SurrogateList$a[i],"&",SurrogateList$b[i],"d_",co,".csv")
  
  #write csv files
  write_csv(d3,file.path("surrogate",file3))
  write_csv(d4,file.path("surrogate",file4))
  write_csv(d5,file.path("surrogate",file5))
  write_csv(d6,file.path("surrogate",file6))
  }
}

##NOW DO THE SAME FOR STUDY 2##
```

